package cn.loveyx815.blog.entity;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String id;

    public String getcPicAdr() {
        return cPicAdr;
    }

    public void setcPicAdr(String cPicAdr) {
        this.cPicAdr = cPicAdr;
    }

    private String cPicAdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.c_title
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cTitle;

    public String getcSecondId() {
        return cSecondId;
    }

    public void setcSecondId(String cSecondId) {
        this.cSecondId = cSecondId;
    }

    public String getcFirstId() {
        return cFirstId;
    }

    public void setcFirstId(String cFirstId) {
        this.cFirstId = cFirstId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.c_content
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.c_uid
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.c_lable_id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cFirstId;
    private String cSecondId;
    private String cLableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.c_pic_adr
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cMd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.c_value
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private Integer cValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.c_title
     *
     * @return the value of t_blog.c_title
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcTitle() {
        return cTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.c_title
     *
     * @param cTitle the value for t_blog.c_title
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcTitle(String cTitle) {
        this.cTitle = cTitle == null ? null : cTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.c_content
     *
     * @return the value of t_blog.c_content
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcContent() {
        return cContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.c_content
     *
     * @param cContent the value for t_blog.c_content
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcContent(String cContent) {
        this.cContent = cContent == null ? null : cContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.c_uid
     *
     * @return the value of t_blog.c_uid
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcUid() {
        return cUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.c_uid
     *
     * @param cUid the value for t_blog.c_uid
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcUid(String cUid) {
        this.cUid = cUid == null ? null : cUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.c_time
     *
     * @return the value of t_blog.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.c_time
     *
     * @param cTime the value for t_blog.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.c_lable_id
     *
     * @return the value of t_blog.c_lable_id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcLableId() {
        return cLableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.c_lable_id
     *
     * @param cLableId the value for t_blog.c_lable_id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcLableId(String cLableId) {
        this.cLableId = cLableId == null ? null : cLableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.c_pic_adr
     *
     * @return the value of t_blog.c_pic_adr
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcMd() {
        return cMd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.c_pic_adr
     *
     * @param cMd the value for t_blog.c_pic_adr
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcMd(String cMd) {
        this.cMd = cMd == null ? null : cMd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.c_value
     *
     * @return the value of t_blog.c_value
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public Integer getcValue() {
        return cValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.c_value
     *
     * @param cValue the value for t_blog.c_value
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcValue(Integer cValue) {
        this.cValue = cValue;
    }
}