package cn.loveyx815.blog.entity;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.c_content
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.c_user
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private Date cTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.c_content
     *
     * @return the value of t_message.c_content
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcContent() {
        return cContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.c_content
     *
     * @param cContent the value for t_message.c_content
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcContent(String cContent) {
        this.cContent = cContent == null ? null : cContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.c_user
     *
     * @return the value of t_message.c_user
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcUser() {
        return cUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.c_user
     *
     * @param cUser the value for t_message.c_user
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcUser(String cUser) {
        this.cUser = cUser == null ? null : cUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.c_time
     *
     * @return the value of t_message.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.c_time
     *
     * @param cTime the value for t_message.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }
}