package cn.loveyx815.blog.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_role
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_name
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_password
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_xb
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private Integer cXb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_img_adr
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cImgAdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_alias
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_jj
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cJj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_dz
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cDz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_star
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.key1
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_attention
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cAttention;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_brith
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private Date cBrith;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_fans
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    private String cFans;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_role
     *
     * @return the value of t_user.c_role
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcRole() {
        return cRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_role
     *
     * @param cRole the value for t_user.c_role
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcRole(String cRole) {
        this.cRole = cRole == null ? null : cRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_name
     *
     * @return the value of t_user.c_name
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_name
     *
     * @param cName the value for t_user.c_name
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_password
     *
     * @return the value of t_user.c_password
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcPassword() {
        return cPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_password
     *
     * @param cPassword the value for t_user.c_password
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcPassword(String cPassword) {
        this.cPassword = cPassword == null ? null : cPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_xb
     *
     * @return the value of t_user.c_xb
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public Integer getcXb() {
        return cXb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_xb
     *
     * @param cXb the value for t_user.c_xb
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcXb(Integer cXb) {
        this.cXb = cXb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_img_adr
     *
     * @return the value of t_user.c_img_adr
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcImgAdr() {
        return cImgAdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_img_adr
     *
     * @param cImgAdr the value for t_user.c_img_adr
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcImgAdr(String cImgAdr) {
        this.cImgAdr = cImgAdr == null ? null : cImgAdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_alias
     *
     * @return the value of t_user.c_alias
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcAlias() {
        return cAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_alias
     *
     * @param cAlias the value for t_user.c_alias
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcAlias(String cAlias) {
        this.cAlias = cAlias == null ? null : cAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_jj
     *
     * @return the value of t_user.c_jj
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcJj() {
        return cJj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_jj
     *
     * @param cJj the value for t_user.c_jj
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcJj(String cJj) {
        this.cJj = cJj == null ? null : cJj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_dz
     *
     * @return the value of t_user.c_dz
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcDz() {
        return cDz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_dz
     *
     * @param cDz the value for t_user.c_dz
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcDz(String cDz) {
        this.cDz = cDz == null ? null : cDz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_star
     *
     * @return the value of t_user.c_star
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcStar() {
        return cStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_star
     *
     * @param cStar the value for t_user.c_star
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcStar(String cStar) {
        this.cStar = cStar == null ? null : cStar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_time
     *
     * @return the value of t_user.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_time
     *
     * @param cTime the value for t_user.c_time
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.key1
     *
     * @return the value of t_user.key1
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.key1
     *
     * @param key1 the value for t_user.key1
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_attention
     *
     * @return the value of t_user.c_attention
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcAttention() {
        return cAttention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_attention
     *
     * @param cAttention the value for t_user.c_attention
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcAttention(String cAttention) {
        this.cAttention = cAttention == null ? null : cAttention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_brith
     *
     * @return the value of t_user.c_brith
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public Date getcBrith() {
        return cBrith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_brith
     *
     * @param cBrith the value for t_user.c_brith
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcBrith(Date cBrith) {
        this.cBrith = cBrith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.c_fans
     *
     * @return the value of t_user.c_fans
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public String getcFans() {
        return cFans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.c_fans
     *
     * @param cFans the value for t_user.c_fans
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    public void setcFans(String cFans) {
        this.cFans = cFans == null ? null : cFans.trim();
    }
}