package cn.loveyx815.blog.dao;

import cn.loveyx815.blog.entity.Comment;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CommentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    Comment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int updateByPrimaryKey(Comment record);

    int getCountById( @Param("id") String id);

    List<Map<String,Object>> getCommentByPage(
            @Param("curpage") int curPage,
            @Param("cursize") int curSize,
            @Param("id") String id);

    List<Map<String ,Object>> getAllCommentByUser(@Param("uid") String uid);
    List<Map<String ,Object>> getCommentForAdmin(
            @Param("curpage") int curpage,
            @Param("cursize") Integer cursize                                  );


    Integer getCommentCount();
}