package cn.loveyx815.blog.dao;

import cn.loveyx815.blog.entity.OneCategory;

public interface OneCategoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int insert(OneCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int insertSelective(OneCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    OneCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(OneCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_onecategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int updateByPrimaryKey(OneCategory record);
}