package cn.loveyx815.blog.dao;

import cn.loveyx815.blog.entity.TwoCategory;

public interface TwoCategoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int insert(TwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int insertSelective(TwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    TwoCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TwoCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_twocategory
     *
     * @mbg.generated Mon Apr 22 16:15:48 GMT+08:00 2019
     */
    int updateByPrimaryKey(TwoCategory record);
}